name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: configure and build
        uses: lukka/run-cmake@v2

        with:
          cmakeAppendedArgs: '-LA -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=11 -DWITH_LUA=ON'
          buildDirectory: '${{ github.workspace }}/build/'

      - name: test
        run: cd build && ctest --output-on-failure
        shell: bash
